language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - which cargo-make || cargo install cargo-make
  - cargo make ci
